version: "2"

linters:
  enable:
    - errcheck
    - funlen
    - goconst
    - godox
    - gosec
    - govet
    - gocyclo
    - gocognit
    - goconst
    - inamedparam
    - ineffassign
    - loggercheck
    - musttag
    - predeclared
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - fmt.Println
        - fmt.Fprintln
        - fmt.Fprintf
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    funlen: #default 60/40
      lines: 245
      statements: 102
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          disabled: true
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: exported
          disabled: true
        - name: function-length
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: get-return
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: unexported-return
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: var-naming
          arguments:
            - []
            - []
            - [{ skipPackageNameChecks: true }]
    gocyclo:
      min-complexity: 30
    gocognit:
      min-complexity: 30

formatters:
  enable:
    - goimports

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 4
