dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
include-regex: ".+Mock"
with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
packages:
  bot/internal/client/github:
