// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "bot/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Ask provides a mock function with given fields: ctx, systemPrompt, messages
func (_m *Client) Ask(ctx context.Context, systemPrompt string, messages []*model.ChatMessage) ([]string, error) {
	ret := _m.Called(ctx, systemPrompt, messages)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*model.ChatMessage) ([]string, error)); ok {
		return rf(ctx, systemPrompt, messages)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []*model.ChatMessage) []string); ok {
		r0 = rf(ctx, systemPrompt, messages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []*model.ChatMessage) error); ok {
		r1 = rf(ctx, systemPrompt, messages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type Client_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - systemPrompt string
//   - messages []*model.ChatMessage
func (_e *Client_Expecter) Ask(ctx interface{}, systemPrompt interface{}, messages interface{}) *Client_Ask_Call {
	return &Client_Ask_Call{Call: _e.mock.On("Ask", ctx, systemPrompt, messages)}
}

func (_c *Client_Ask_Call) Run(run func(ctx context.Context, systemPrompt string, messages []*model.ChatMessage)) *Client_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*model.ChatMessage))
	})
	return _c
}

func (_c *Client_Ask_Call) Return(_a0 []string, _a1 error) *Client_Ask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Ask_Call) RunAndReturn(run func(context.Context, string, []*model.ChatMessage) ([]string, error)) *Client_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
